### ISSUE TITLE
FreeNas logo

### ISSUE THREAD

**Issue by JM2K69** [adilio/ps-design#13]
Hi,

I create a **PowerShell** module to interact with **FreeNas** and **TrueNas**
server with API. It's possible to design a logo for my powershell module. I attached some official Logo created by the **FreeNas** Enterprise. Here my project repo : [Link](https://github.com/jm2k69/freenas)
![freenas_logo_flat](https://user-images.githubusercontent.com/17923944/71521475-46cf2080-28c1-11ea-98fc-89f67f0d8672.png)
![RUTO3H65_400x400](https://user-images.githubusercontent.com/17923944/71521480-48004d80-28c1-11ea-8c78-6763ae84227b.jpg)
![TrueNASPro_Logo](https://user-images.githubusercontent.com/17923944/71521484-4a62a780-28c1-11ea-8532-7c8dd3eb3d51.png)
![RUTO3H65_400x400](https://user-images.githubusercontent.com/17923944/71521493-50f11f00-28c1-11ea-816f-14223b83edc9.jpg)

**Comment by adilio** [comment]
Heya @JM2K69, apologies for the delay. Just wanted you to know, I'm shutting down the issues portion of this site. 😢
Unfortunately, due to competing priorities, and life things that have come up, I no longer have time to dedicate to all design projects, and so I have to be a bit choosy with what I can take on. I also have to work on my mental well-being and work-life balance.
Hope you understand, and good luck with your future endeavors! 🤗

**Comment by JM2K69** [comment]
Thank you man !
